[[OpenFOAM_com]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fed917b9cf175b93a8b78bf2278b62d2f219546c"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[OpenFOAM_com.download]]
    sha256 = "1fcc07342522cf62e33f4ba2011aac3245f86628cbc00bfe482b1ed21ec1c151"
    url = "https://github.com/JuliaBinaryWrappers/OpenFOAM_com_jll.jl/releases/download/OpenFOAM_com-v2312.0.1+0/OpenFOAM_com.v2312.0.1.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[OpenFOAM_com]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2965d70090d5e05680ec252709a814657d998fee"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[OpenFOAM_com.download]]
    sha256 = "49c93cffca82a4f96cbe7acf265ab615a64035925d36d02b63e2a29aada7d7b2"
    url = "https://github.com/JuliaBinaryWrappers/OpenFOAM_com_jll.jl/releases/download/OpenFOAM_com-v2312.0.1+0/OpenFOAM_com.v2312.0.1.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[OpenFOAM_com]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a53c20544cdf590cd4d8adc267bcc8e3dd2e8691"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[OpenFOAM_com.download]]
    sha256 = "6e027be6b79c2f313bd6af70faadc0bc11132b89e68288c084f01c5e357adc8e"
    url = "https://github.com/JuliaBinaryWrappers/OpenFOAM_com_jll.jl/releases/download/OpenFOAM_com-v2312.0.1+0/OpenFOAM_com.v2312.0.1.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
